.PHONY: clean All

All:
	@echo "----------Building project:[ fparticle - Debug ]----------"
	@"$(MAKE)" -f  "fparticle.mk"
clean:
	@echo "----------Cleaning project:[ fparticle - Debug ]----------"
	@"$(MAKE)" -f  "fparticle.mk" clean
