#pragma once
#include <fmath/physics.h>
#include "State.h"

double electronTemp(double);
double electronTempOriginal(double);
double ionTemp(double);
double radialVel(double);
double keplAngVel(double);
double angularVel(double);
double sqrdSoundVel(double);
double height_fun(double);
double costhetaH(double);
double massDensityADAF(double);
double auxCD(double);
double electronDensity(double);
double electronDensityTheta(double,double);
double ionDensity(double);
double magneticField(double);
double gAcc(double);
double accRateADAF(double);
double accRateColdDisk(double);
double accretionTime(double);
double accretionTimer1r2(double,double);
double qie(double,double,double);
double qie_beta(double,double,double);
double dlogrho_dlogr(double);
double Qplus(double,double,double);
double Qmin_func(double,Matrix,Matrix,Vector,State&);
double volume(double);
