.PHONY: clean All

All:
	@echo "----------Building project:[ probMatrix - Release ]----------"
	@"$(MAKE)" -f  "probMatrix.mk"
clean:
	@echo "----------Cleaning project:[ probMatrix - Release ]----------"
	@"$(MAKE)" -f  "probMatrix.mk" clean
