.PHONY: clean All

All:
	@echo "----------Building project:[ probMatrix - Debug ]----------"
	@"$(MAKE)" -f  "probMatrix.mk"
clean:
	@echo "----------Cleaning project:[ probMatrix - Debug ]----------"
	@"$(MAKE)" -f  "probMatrix.mk" clean
