.PHONY: clean All

All:
	@echo "----------Building project:[ fmath - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/fmath" && "$(MAKE)" -f  "fmath.mk"
	@echo "----------Building project:[ fparameters - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/fparameters" && "$(MAKE)" -f  "fparameters.mk"
	@echo "----------Building project:[ fparticle - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/fparticle" && "$(MAKE)" -f  "fparticle.mk"
	@echo "----------Building project:[ flosses - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/flosses" && "$(MAKE)" -f  "flosses.mk"
	@echo "----------Building project:[ fluminosities - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/fluminosities" && "$(MAKE)" -f  "fluminosities.mk"
	@echo "----------Building project:[ inout - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/inout" && "$(MAKE)" -f  "inout.mk"
	@echo "----------Building project:[ ionTori - Release ]----------"
	@"$(MAKE)" -f  "ionTori.mk"
clean:
	@echo "----------Cleaning project:[ fmath - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/fmath" && "$(MAKE)" -f  "fmath.mk"  clean
	@echo "----------Cleaning project:[ fparameters - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/fparameters" && "$(MAKE)" -f  "fparameters.mk"  clean
	@echo "----------Cleaning project:[ fparticle - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/fparticle" && "$(MAKE)" -f  "fparticle.mk"  clean
	@echo "----------Cleaning project:[ flosses - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/flosses" && "$(MAKE)" -f  "flosses.mk"  clean
	@echo "----------Cleaning project:[ fluminosities - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/fluminosities" && "$(MAKE)" -f  "fluminosities.mk"  clean
	@echo "----------Cleaning project:[ inout - Release ]----------"
	@cd "/home/eduardog/FACULTAD/DOCTORADO/Tori/neiwork/radproc_linux/lib/inout" && "$(MAKE)" -f  "inout.mk"  clean
	@echo "----------Cleaning project:[ ionTori - Release ]----------"
	@"$(MAKE)" -f  "ionTori.mk" clean
