.PHONY: clean All

All:
	@echo "----------Building project:[ ionTori - Debug ]----------"
	@"$(MAKE)" -f  "ionTori.mk"
clean:
	@echo "----------Cleaning project:[ ionTori - Debug ]----------"
	@"$(MAKE)" -f  "ionTori.mk" clean
