.PHONY: clean All

All:
	@echo "----------Building project:[ fparameters - Debug ]----------"
	@"$(MAKE)" -f  "fparameters.mk"
clean:
	@echo "----------Cleaning project:[ fparameters - Debug ]----------"
	@"$(MAKE)" -f  "fparameters.mk" clean
