.PHONY: clean All

All:
	@echo "----------Building project:[ fmath - Debug ]----------"
	@"$(MAKE)" -f  "fmath.mk"
clean:
	@echo "----------Cleaning project:[ fmath - Debug ]----------"
	@"$(MAKE)" -f  "fmath.mk" clean
